######### NORMAL OPERATION  ###########

### Read all pizzas
GET http://localhost:3000/films


### Read pizza identified by 2
GET http://localhost:3000/films/2
### Create a pizza
POST http://localhost:3000/films
Content-Type: application/json

{
    "title":"Magic Green",
    "content":"Epinards, Brocolis, Olives vertes, Basilic",
    "duration":120,
    "budget":1200000,
    "link":"taRace.fr"
}